# Generated by Django 3.2.8 on 2022-01-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('idnum', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('order', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
            ],
        ),
    ]
