# Generated by Django 3.2.8 on 2022-01-27 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pemain', '0004_auto_20220127_2234'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
