# Generated by Django 3.2.8 on 2022-02-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemain', '0005_delete_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='timeofendreserve2',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserve',
            name='timeofreserve2',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
