# Generated by Django 3.2.8 on 2022-02-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemain', '0006_auto_20220201_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipments', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('borrowed', models.CharField(max_length=100)),
                ('available', models.CharField(max_length=100)),
            ],
        ),
    ]
