# Generated by Django 3.2.8 on 2022-02-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemain', '0007_equipments'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='status',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
