# Generated by Django 3.2.8 on 2022-02-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemain', '0009_auto_20220203_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('sales', models.IntegerField()),
            ],
        ),
    ]
