# Generated by Django 3.2.8 on 2022-02-03 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pemain', '0010_sales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='product',
            new_name='order1',
        ),
    ]
