# Generated by Django 4.0.3 on 2022-03-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemain', '0012_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='idnum',
            field=models.CharField(max_length=100),
        ),
    ]
